config/routes.rb
Rails.application.routes.draw do

# 会員
  scope module: 'public' do
    root :to =>'homes#top'
    get "/about"=>'homes#about'

    devise_for :customers,skip: [:passwords], controllers: { registrations: 'public/registrations'}
    get "customers/mypage"=>'customers#show'
    resources :customers, only: [:edit, :update] do
      get :unsubscribe, on: :member
      patch :defection, on: :member
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      delete :destroy_all, on: :collection
    end
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create] do
      post :order_preconfirm, on: :collection
      get :complete, on: :collection
    end

    resources :shipping_addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :searches, only: [:search_item, :search_genre] do
      get :search_item, on: :collection
      get :search_genre, on: :collection
    end
  end


  # 管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root :to =>'homes#top'
    get "/about"=>'homes#about'

    resources :customers, only: [:index, :show, :edit, :update] do
      get :index_order, on: :member
    end
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :edit, :create, :update]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    resources :searches, only: [:search_item] do
       get :search_item, on: :collection
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items
  has_many :order_details
  belongs_to :genre

  validates :name, presence:true
  validates :summary, presence:true
  validates :price_non_tax, presence:true
  validates :image, presence:true

  has_one_attached:image

  enum is_active: { 販売中: true, 販売停止中: false }

 #引数に取得件数を渡し、作成日で降順ソートした商品を返却する
  scope :get_items_sort_of_CreateDate, -> (number_of_display) {where(is_active: true).order("created_at": :desc).limit(number_of_display.to_i)}

  #######インスタンスメソッド######

  def get_image(width, height)
    unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.png')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price_non_tax * 1.1).floor
  end

  def get_item_image
    (image.attached?) ? image : 'no_image.jpg'
  end


  #######クラスメソッド######

  def self.search_item_fnc(item_name)
    search_result = Item.where(is_active: true).where('name LIKE ?', "%#{item_name}%")
    return search_result
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController

  skip_before_action :authenticate_admin!, only: [:index, :show]

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "商品を新規作成しました"
       redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品を更新しました"
       redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :summary, :price_non_tax, :genre_id, :is_active)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_index.html.erb
<table class="table table-hover">
  <thead class="thead-light">
    <tr class="table-secondary">
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <% items.each do |item| %>
  <tbody>
    <tr>
      <th><%= item.id %></th>
      <th>
        <%= link_to admin_item_path(item.id) do %>
          <%= item.name %>
        <% end %>
      </th>
      <th>¥ <%= item.price_non_tax.to_s(:delimited) %></th>
      <th><%= item.genre.name %></th>
      <th><%= item.is_active %></th>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/admin/items/_show.html.erb
<table class="table table-borderless">
  <tr>
    <th class="item_name_column">商品名</th>
    <td class="item_name"><u><%= item.name %></u></td>
  </tr>
  <tr>
    <th class="item_column">商品説明</th>
    <td class="item_info"><%= item.summary %></td>
  </tr>
  <tr>
    <th class="item_column">ジャンル</th>
    <td class="item_info"><%= item.genre.name %></td>
  </tr>
  <tr>
    <th class="item_column">
      税抜価格</br>
      （税込価格）
    </th>
    <td class="item_info align-middle">
      ¥ <%= item.price_non_tax.to_s(:delimited) %>（¥ <%= item.with_tax_price.to_s(:delimited) %>）
    </td>
  </tr>
  <tr>
    <th class="item_column">販売ステータス</th>
    <td class="item_info"><%= item.is_active %></td>
  </tr>
</table>

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto">
      <div class="admin_item_edit">
        <div class="text-error">
          <%= render 'layouts/public/errors', obj: @item %>
        </div>
          <h4 class="item_edit mt-2 mb-3">商品編集</h4>
           <%= form_with model:@item, url:admin_item_path(@item.id) do |f| %>
          <div class="form_group col-8">
            <%= f.label :image, "商品画像" %></br>
            <%= f.file_field :image,  accept: 'image/*' %>

          </div>
          <div class="form_group col-8 pt-2 pb-2">
            <%= f.label :name, "商品名" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form_group col-8 pt-2 pb-2">
            <%= f.label :summary, "商品説明" %>
            <%= f.text_area :summary, size: "40x8" , class: "form-control" %>
          </div>

          <div class="form_group col-8 pt-2 pb-2">
            <%= f.label :genre_id, 'ジャンル' %></br>
            <%= f.collection_select :genre_id, @genres,:id,:name %>
          </div>

          <div class="form_group col-8 pt-2 pb-2">
            <%= f.label :price_non_tax, "税抜価格(¥)" %>
            <%= f.text_field :price_non_tax, class: "form-control" %>
          </div>

          <div class="form_botton col-8 pt-2 pb-2">
            <%= f.label :is_active, "販売ステータス" %>
            <%= f.radio_button :is_active, :"販売中" %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, :"販売停止中" %>
            <%= f.label :is_active, "販売停止中" %>
          </div>

          <div class="text_center col-8">
           <%= f.submit "変更を保存" ,class: "btn btn-outline-dark font-weight-bold form-button-common btn-lg" %>
           <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row" style = "margin-top: 50px;">
    <div class="col-md-2 offset-md-1">
      <h4 class="font-weight-bold"><u>商品一覧</u></h4>
    </div>
  </div>
  <div class="row mt-3 justify-content-center">
    <div class="col-md-8">
      <%= render 'index', items: @items %>
      <%= paginate @items %>
    </div>
    <div class="col-md-1">
      <%= link_to new_admin_item_path do %>
        <i class="plus_button fas fa-plus-circle fa-3x"></i>
        <!--<div type="button" class="btn btn-outline-dark font-weight-bold form-button-common btn-circle" style="border-radius: 50%;">＋</div>-->
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mx-auto">
      <div class="admin_item_new">
        <div class="text-error">
          <%= render 'layouts/public/errors', obj: @item %>
        </div>
        <h4 class="item_new mt-2 mb-3">商品新規登録</h4>
          <%= form_with model:@item, url:admin_items_path do |f| %>
        <div class="form_group col-8">
          <%= f.label :image, "商品画像" %></br>
          <%= f.file_field :image, accept: 'image/*' %>
        </div>
        <div class="form_group col-8 pt-2 pb-2">
          <%= f.label :name, "商品名" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form_group col-8 pt-2 pb-2">
          <%= f.label :summary, "商品説明" %>
          <%= f.text_area :summary, size: "40x8" , class: "form-control" %>
        </div>
        <div class="form_group col-8 pt-2 pb-2">
          <%= f.label :genre_id, 'ジャンル' %></br>
          <%= f.collection_select :genre_id, @genres,:id,:name %>
        </div>
        <div class="form_group col-8 pt-2 pb-2">
          <%= f.label :price_non_tax, "税抜価格(¥)" %>
          <%= f.text_field :price_non_tax, class: "form-control" %>
        </div>
        <div class="form_botton col-8 pt-2 pb-2">
          <%= f.label :is_active, "販売ステータス" %>
          <%= f.radio_button :is_active, :"販売中" %>
          <%= f.label :is_active, "販売中" %>
          <%= f.radio_button :is_active, :"販売停止中" %>
          <%= f.label :is_active, "販売停止中" %>
        </div>
        <div class="text_center col-8">
          <%= f.submit "新規登録" ,class: "btn btn-outline-dark font-weight-bold form-button-common btn-lg" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div style="margin-top: 50px;">
    <h4 class="font-weight-bold" style="margin-left: 100px;" ><u>商品詳細</u></h4>
  </div>
  <div class="row mt-5">
    <div class="col-md-3 offset-md-1">
      <%= image_tag @item.get_item_image, size:"350x350" %>
    </div>
    <div class="col-md-7 offset-md-1" style="text-align: center;">
      <%= render 'show', item: @item %>
      <%= link_to edit_admin_item_path(@item) do %>
        <button type="button" class="btn btn-outline-dark font-weight-bold form-button-common">編集する</button>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>