config/routes.rb
Rails.application.routes.draw do

# 会員
  scope module: 'public' do
    root :to =>'homes#top'
    get "/about"=>'homes#about'

    devise_for :customers,skip: [:passwords], controllers: { registrations: 'public/registrations'}
    get "customers/mypage"=>'customers#show'
    resources :customers, only: [:edit, :update] do
      get :unsubscribe, on: :member
      patch :defection, on: :member
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      delete :destroy_all, on: :collection
    end
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create] do
      post :order_preconfirm, on: :collection
      get :complete, on: :collection
    end

    resources :shipping_addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :searches, only: [:search_item, :search_genre] do
      get :search_item, on: :collection
      get :search_genre, on: :collection
    end
  end


  # 管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root :to =>'homes#top'
    get "/about"=>'homes#about'

    resources :customers, only: [:index, :show, :edit, :update] do
      get :index_order, on: :member
    end
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :edit, :create, :update]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    resources :searches, only: [:search_item] do
       get :search_item, on: :collection
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :items,through: :cart_items

  validates :first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :address, :phone_number, :email, presence: true
  validates :post_code, {length: {is: 7} }
  validates :phone_number, length: { minimum: 10, maximum: 11 }

  enum is_deleted: { 有効: false, 退会: true }


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
       @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       flash[:notice] = "会員情報を更新しました"
       redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  def index_order
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.order("created_at DESC").page(params[:page])
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9 mx-auto">
      <div class="text-error">
        <%= render 'layouts/public/errors', obj: @customer %>
      </div>
        <h4 class="admin-customer_edit"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
        <%= form_with model:@customer,url: admin_customer_path(@customer.id), method: :patch do |f| %>
        <table class="table table-borderless">
          <thead>
            <tr>
              <th>会員ID</th>
              <td><%= @customer.id %></td>
            </tr>
            <tr>
              <th>氏名</th>
              <td><%= f.text_field :last_name, class: "last_name_field form_control" %> <%= f.text_field :first_name, class: "form_control" %></td>
            </tr>
            <tr>
              <th>フリガナ</th>
              <td><%= f.text_field :last_name_kana, class: "last_name_kana_field form_control" %> <%= f.text_field :first_name_kana, class: "form_control" %></td>
            </tr>
            <tr>
              <th>郵便番号</th>
              <td><%= f.text_field :post_code, class: "form_control" %></td>
            </tr>
            <tr>
              <th>住所</th>
              <td><%= f.text_field :address, size: "60x2" , class: "form_control" %></td>
            </tr>
            <tr>
              <th>電話番号</th>
              <td><%= f.text_field :phone_number, class: "form_control" %></td>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <td><%= f.email_field :email, class: "form_control" %></td>
            </tr>
            <tr>
              <th>会員ステータス</th>
              <div class="customer_field">
                <td>
                  <%= f.radio_button :is_deleted, :"有効" %>
                  <%= f.label :is_deleted, "有効" %>
                  <%= f.radio_button :is_deleted, :"退会" %>
                  <%= f.label :is_deleted, "退会" %>
                </td>
              </div>
            </tr>
          </thead>
        </table>
      <div class="row">
        <div class="btn-group col-3 pl-10 mx-auto">
        <%= f.submit "変更を保存", class: "btn btn-outline-dark font-weight-bold form-button-common" %>
        <% end %>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 mx-auto">
      <h4 class="customer-index mb-4">会員一覧</h4>
      <table class="table table-hover">
        <thead class="thead-light">
          <tr class="table-secondary">
           <th>会員ID</th>
           <th>氏名</th>
           <th>メールアドレス</th>
           <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <th><%= customer.id %></th>
            <th><%= link_to admin_customer_path(customer.id) do %>
                <%= customer.last_name %><%= customer.first_name %></th>
                <% end %>
            <th><%= customer.email %></th>
            <th><%= customer.is_deleted %></th>
          </tr>
        </tbody>
        <% end %>
      </table>
     <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/index_order.html.erb
<div class="container">
   <div class="row">
    <div class="col-md-8 mx-auto">
      <h4 class="admin_customer_index_order mb-4 mt-3"><%= @customer.last_name %><%= @customer.first_name %>さんの注文履歴</h4>
        <table class="table table-hover">
          <thead class="thead-light">
            <tr class="table-secondary">
             <th>購入日時</th>
             <th>注文個数</th>
             <th>注文ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
            <tr>
             <th><%= link_to admin_order_path(order.id) do %>
                  <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></th>
                 <% end %>
             <th><%= order.order_details.sum(:amount) %></th>
             <th><%= order.status_i18n %></th>
            </tr>
          </tbody>
          <% end %>
        </table>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <h4 class="admin-customer-show">
        <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
      </h4>
      <table class="table table-borderless">
        <thead>
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= @customer.last_name %> <%= @customer.first_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= @customer.post_code %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= @customer.phone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td><%= @customer.is_deleted %></td>
          </tr>
        </thead>
      </table>
      <div class="btn-toolbar">
        <div class="btn-group">
          <div class="row mr-5 ml-2">
            <%= link_to edit_admin_customer_path(@customer) do %>
            <button type="button" class="btn btn-outline-dark font-weight-bold form-button-common">編集する</button>
            <% end %>
          </div>
          <div class="row">
            <%= link_to index_order_admin_customer_path(@customer.id) do %>
            <button type="button" class="btn btn-outline-dark font-weight-bold form-button-common">注文履歴一覧を見る</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>