config/routes.rb
Rails.application.routes.draw do

# 会員
  scope module: 'public' do
    root :to =>'homes#top'
    get "/about"=>'homes#about'

    devise_for :customers,skip: [:passwords], controllers: { registrations: 'public/registrations'}
    get "customers/mypage"=>'customers#show'
    resources :customers, only: [:edit, :update] do
      get :unsubscribe, on: :member
      patch :defection, on: :member
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      delete :destroy_all, on: :collection
    end
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create] do
      post :order_preconfirm, on: :collection
      get :complete, on: :collection
    end

    resources :shipping_addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :searches, only: [:search_item, :search_genre] do
      get :search_item, on: :collection
      get :search_genre, on: :collection
    end
  end


  # 管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root :to =>'homes#top'
    get "/about"=>'homes#about'

    resources :customers, only: [:index, :show, :edit, :update] do
      get :index_order, on: :member
    end
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :edit, :create, :update]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    resources :searches, only: [:search_item] do
       get :search_item, on: :collection
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/admin/_errors.html.erb
<% if obj.errors.any? %>
<div class = err_area>
  <div id="error_explanation">
    <ul class="err_mes_area ">
      <% obj.errors.full_messages.each do |message| %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        <%= message %>
      </div>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/layouts/admin/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <p class="footertopline"></p>
  	<div class='row footer_area'>
    	<div class='mx-auto'>
    	  FOLLOW US ON
    	  <span class="icon">
    	    <i class="fab fa-twitter-square"></i>
    	  </span>
    	  <span class="icon">
    	    <i class="fab fa-instagram-square"></i>
    	  <span class="icon">
    	  </span>
    	    <i class="fab fa-facebook-square"></i>
    	  </span>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<header class="Header">
  <nav class="navbar navbar-expand-lg navbar-light p-3" style="background-color:#fffacd;" >
    <div class="container">
      <a class="navbar-brand" href="/admin">
        <div class= 'img_wrap_kuni'>
          <%= image_tag('Nagano_Cake_Logo.png', size: '90x90') %>
        </div>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_items_path,class: 'nav-link text-dark heaedr-link' do %>
              <i class="fas fa-cheese"></i><b>商品一覧</b>
            <% end %>
          </li>
          <li>
            <%= link_to admin_customers_path,class: 'nav-link text-dark heaedr-link' do %>
              <i class="fas fa-user-friends"></i><b>会員一覧</b>
            <% end %>
          </li>
          <li>
            <%= link_to admin_root_path,class: 'nav-link text-dark heaedr-link' do %>
              <i class="fas fa-clipboard-check"></i><b>注文履歴一覧</b>
            <% end %>
          </li>
          <li>
            <%= link_to admin_genres_path,class: 'nav-link text-dark heaedr-link' do %>
              <i class="fas fa-folder-open"></i><b>ジャンル一覧</b>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark heaedr-link' do %>
              <i class="fas fa-sign-in-alt"></i><b>ログアウト</b>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to about_path, class: 'nav-link text-dark heaedr-link' do %>
              <i class="fas fa-exclamation-circle"></i><b>About</b>
            <% end %>
          </li>
          <li>
            <%= link_to admin_items_path, class: 'nav-link text-dark heaedr-link' do %>
              <i class="fas fa-cheese"></i><b>商品一覧</b>
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path, class: 'nav-link text-dark heaedr-link' do %>
              <i class="fas fa-user-plus"></i><b>新規登録</b>
            <% end %>
          </li>
          <li>
            <%= link_to new_admin_session_path, class: 'nav-link text-dark heaedr-link' do %>
              <i class="fas fa-sign-in-alt"></i><b>ログイン</b>
            <% end %>
          </li>
          <% end %>
        </ul>
        <ul class="navbar-nav">
          <%= form_with url: search_item_admin_searches_path, method: :get do |f| %>
          <div class="container h-100">
            <div class="d-flex justify-content-center h-100">
              <div class="searchbar">
                <%= f.text_field :search_text, class: "search_input", placeholder: "商品名検索..." %>
                <%= f.button :type => "submit", style: 'border-style: none; background: none;', class: "search_icon" do %>
                  <i class="fas fa-search"></i>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="Contents">
    <%= render 'layouts/admin/header' %>
    <main>
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </main>
    <%= render 'layouts/admin/footer' %>
  </body>
</html>