config/routes.rb
Rails.application.routes.draw do

# 会員
  scope module: 'public' do
    root :to =>'homes#top'
    get "/about"=>'homes#about'

    devise_for :customers,skip: [:passwords], controllers: { registrations: 'public/registrations'}
    get "customers/mypage"=>'customers#show'
    resources :customers, only: [:edit, :update] do
      get :unsubscribe, on: :member
      patch :defection, on: :member
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      delete :destroy_all, on: :collection
    end
    resources :items, only: [:index, :show]
    resources :orders, only: [:index, :show, :new, :create] do
      post :order_preconfirm, on: :collection
      get :complete, on: :collection
    end

    resources :shipping_addresses, only: [:index, :edit, :create, :update, :destroy]

    resources :searches, only: [:search_item, :search_genre] do
      get :search_item, on: :collection
      get :search_genre, on: :collection
    end
  end


  # 管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root :to =>'homes#top'
    get "/about"=>'homes#about'

    resources :customers, only: [:index, :show, :edit, :update] do
      get :index_order, on: :member
    end
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :edit, :create, :update]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    resources :searches, only: [:search_item] do
       get :search_item, on: :collection
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
       flash[:notice] = "ジャンルを新規作成しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
       flash[:notice] = "ジャンル名を更新しました"
       redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="text-error">
        <%= render 'layouts/public/errors', obj: @genre %>
    </div>
    <div class="genre-form col-8 mx-auto">
        <h4 class="genre_edit mb-4">ジャンル編集</h4>
          <%= form_with model:@genre, url:admin_genre_path(@genre) do |f| %>
          <%= f.label :name, "ジャンル名" %>
          <%= f.text_field :name %>
      <div class="btn-group ml-5">
          <%= f.submit "変更を保存", class: 'btn btn-outline-dark font-weight-bold form-button-common' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="text-error">
        <%= render 'layouts/public/errors', obj: @genre %>
    </div>
    <div class="col-sm-12 col-md-8 mx-auto">
      <div class="genre-form mb-4 mt-4">
        <h4 class="genre_index">ジャンル一覧・追加</h4>
            <%= form_with model:@genre, url:admin_genres_path do |f| %>
            <%= f.label :name, "ジャンル名" %>
            <%= f.text_field :name %>
          <div class="btn-group ml-5">
            <%= f.submit "新規登録", class: 'btn btn-outline-dark font-weight-bold form-button-common btn-lg' %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 mx-auto">
      <table class="table table-hover">
        <thead class="thead-light">
          <tr class="table-secondary">
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
          <% @genres.each do |genre| %>
        <tbody>
          <tr>
            <th><%= genre.name %></th>
            <td><%= link_to edit_admin_genre_path(genre.id) do %>
                <button type="button" class="btn btn-outline-dark font-weight-bold form-button-common">編集する</button>
                <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>